#' Plotting distributions by group variables.
#'
#' @param data Input data frame.
#' @param metric_var Metric variable whose distribution is displayed.
#' @param group_var Categorical variable that is used to group the metric variable visually.
#' @param plot_type Type of plot, either "both", "ridge_plot" or "box_plot". Default is "both" (Combine both plot types).
#'
#' @return A `ggplot` object.
#' @importFrom magrittr %>%
#' @export
#'
plot_dist <- function(data, metric_var, group_var, plot_type = "both") {
  checkmate::check_data_frame(data)

  metric_var <- rlang::sym(metric_var)
  group_var <- rlang::sym(group_var)

  plot <- data %>%
    ggplot2::ggplot(
      ggplot2::aes(x = {{ metric_var }}, y = as.factor( {{ group_var }} ))
    ) +
    ggplot2::labs(y = group_var)

  if (plot_type == "both") {
    width_val <- 1 / log2(
      data %>%
        dplyr::pull(group_var) %>%
        as.factor() %>%
        nlevels()
    )
    if (width_val > 0.4) {
      width_val <- 0.4
    }
    plot +
      ggridges::geom_density_ridges(scale = 0.75) +
      ggplot2::geom_boxplot(width = width_val)
  } else if (plot_type == "ridge_plot") {
    plot +
      ggridges::geom_density_ridges(scale = 0.75)
  } else if (plot_type == "box_plot") {
    plot +
      ggplot2::geom_boxplot()
  }
}

#' Plotting summarized data frames generated by `count_data()`.
#'
#' @param data Input `data.frame` (function is designed to work with data generated from `count_data()`).
#' @param x_var Single `character` value indicating which variable is displayed on the x axis.
#' @param fill_var Single `character` value indicating which variable is used to fill the plot (`fill` argument in `ggplot()`). Default is `NULL`.
#' @param facet_var Single `character` value indicating which variable is used to facet the plot (via `facet_wrap()`) . Default is `NULL`.
#' @param exclude_na `logical` value indicating whether to exclude `NA`s in the plot (checks all variables indicated via other parameters). Default is `FALSE`.
#'
#' @return A `ggplot` object.
#' @importFrom magrittr %>%
#' @export
#'
plot_count <- function(data, x_var, fill_var = NULL, facet_var = NULL, exclude_na = FALSE) {
  checkmate::assert_data_frame(data)
  checkmate::assert(
    check_character(x_var),
    check_true(length(x_var) == 1),
    combine = "and"
  )

  x_var <- rlang::sym(x_var)

  if (!is.null(fill_var)) {
    fill_var <- rlang::sym(fill_var)
  }

  if (!is.null(facet_var)) {
    facet_var <- rlang::sym(facet_var)
  }

  if (exclude_na == FALSE) {
    df <- data
  } else {
    df <- data %>%
      dplyr::ungroup() %>%
      dplyr::filter(dplyr::if_all(c( {{ x_var }}, {{ fill_var }}, {{ facet_var }} ), ~ !is.na(.)))
  }
  df
  plot <- df %>%
    ggplot2::ggplot(ggplot2::aes(x = as.factor( {{ x_var }} ), y = n, fill = {{ fill_var }} )) +
    ggplot2::labs(x = x_var) +
    ggplot2::geom_col()

  if (is.null(facet_var)) {
    plot
  } else {
    plot +
      ggplot2::facet_wrap(ggplot2::vars(as.factor( {{ facet_var }} )))
  }
}

#' Plotting summarized data frames generated by `rel_freq_data()`.
#'
#' @param data Input `data.frame` (function is designed to work with data generated from `rel_freq_data()`).
#' @param x_var Single `character` value indicating which variable is displayed on the x axis.
#' @param fill_var Single `character` value indicating which variable is used to fill the plot (`fill` argument in `ggplot()`).
#' @param facet_var #' @param facet_var Single `character` value indicating which variable is used to facet the plot (via `facet_wrap()`) . Default is `NULL`.
#' @param exclude_na `logical` value indicating whether to exclude `NA`s in the plot (checks all variables indicated via other parameters). Default is `FALSE`.
#'
#' @return A `ggplot` object.
#' @importFrom magrittr %>%
#' @export
#'
plot_rel_freq <- function(data, x_var, fill_var, facet_var = NULL, exclude_na = FALSE) {
  checkmate::assert_data_frame(data)
  checkmate::assert(
    check_character(x_var),
    check_true(length(x_var) == 1),
    combine = "and"
  )
  checkmate::assert(
    check_character(fill_var),
    check_true(length(fill_var) == 1),
    combine = "and"
  )

  sum_test <- data %>%
    dplyr::group_by(dplyr::across( {{ x_var }} )) %>%
    dplyr::summarise(sum = sum(rel_freq)) %>%
    dplyr::distinct(sum) %>%
    dplyr::pull()

  checkmate::assert_true(all(sum_test == 1))

  x_var <- rlang::sym(x_var)
  fill_var <- rlang::sym(fill_var)

  if (!is.null(facet_var)) {
    facet_var <- rlang::sym(facet_var)
  }

  if (exclude_na == FALSE) {
    df <- data
  } else {
    df <- data %>%
      dplyr::ungroup() %>%
      dplyr::filter(dplyr::if_all(c( {{ x_var }}, {{ fill_var }}, {{ facet_var }} ), ~ !is.na(.)))
  }
  df
  plot <- df %>%
    ggplot2::ggplot(ggplot2::aes(x = as.factor( {{ x_var }} ), y = rel_freq, fill = as.factor( {{ fill_var }} ))) +
    ggplot2::labs(x = x_var, y = "", fill = fill_var) +
    ggplot2::geom_col() +
    ggplot2::scale_y_continuous(labels = scales::percent_format())

  if (is.null(facet_var)) {
    plot
  } else {
    plot +
      ggplot2::facet_wrap(ggplot2::vars(as.factor( {{ facet_var }} )))
  }
}


